spring:
  datasource:
    url: jdbc:mysql://localhost:3306/message_db?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
      pool-name: HikariPool-Message
  
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        show_sql: true
        use_sql_comments: true
        jdbc:
          batch_size: 100
          fetch_size: 50
        order_inserts: true
        order_updates: true
        generate_statistics: true
        cache:
          use_second_level_cache: true
          use_query_cache: true
          region.factory_class: org.hibernate.cache.jcache.internal.JCacheRegionFactory
          provider_class: org.ehcache.jsr107.EhcacheCachingProvider
    open-in-view: false

# Actuator配置
management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        message.processing.time: true
      sla:
        message.processing.time: 100ms,500ms,1s

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.testdemo.demo: DEBUG 